In [1]:
import torch
import pandas as pd
from run_grid_experiments_baybe import run_grid_experiments

seeds = [0]
n_inits = [4, 10]
noise_levels = [0]
# budgets = [10, 20, 50]
noise_bools = [True, False]
budget = 10

run_grid_experiments(seeds, n_inits, noise_levels, noise_bools, budget)

ModuleNotFoundError: No module named 'ray'

In [10]:
df = pd.DataFrame(columns=["n_init", "noise_level", "seed", "noise_bool", "best"])
for noise_bool in noise_bools:
    for n_init in n_inits:
        for noise_level in noise_levels:
            for seed in seeds:
                X, Y, Y_real, model = torch.load(f"results/Schwe_n_init_{n_init}_noiselvl_{noise_level}_budget_{budget}_seed_{seed}_noise_{noise_bool}.pt")
                sliding_min = torch.zeros(Y.shape[0])
                for i in range(Y_real.shape[0]):
                    sliding_min[i] = Y_real[:i+1].min().item()
                df = pd.concat([df, pd.DataFrame({"n_init": [n_init], "noise_level": [noise_level], "seed": [seed], "noise_bool": [noise_bool], "best": [sliding_min[-1].item()]})])
                
df

C:\Users\queim\AppData\Local\Temp\ipykernel_16892\636701015.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame({"n_init": [n_init], "noise_level": [noise_level], "seed": [seed], "noise_bool": [noise_bool], "best": [sliding_min[-1].item()]})])

  n_init noise_level seed noise_bool        best
0      4          10    0       True  207.341003
0      4          10    1       True   42.158676
0      4         100    0       True  120.417244
0      4         100    1       True   42.158676
0     10          10    0       True    1.374434
0     10          10    1       True   42.158676
0     10         100    0       True  102.431664
0     10         100    1       True   42.158676
0      4          10    0      False  118.466827
0      4          10    1      False    0.138172
0      4         100    0      False  118.751045
0      4         100    1      False   13.000295
0     10          10    0      False    0.007694
0     10          10    1      False    0.265530
0     10         100    0      False   25.227522
0     10         100    1      False    0.034306

In [11]:
df_no_noise = df[df["noise_bool"] == False]
df_noise = df[df["noise_bool"] == True]
# df = df.groupby(["n_init", "noise_level", "noise_bool"]).agg({"min": ["mean", "std"]})
df_no_noise = df_no_noise.groupby(["n_init", "noise_level"]).agg({"best": ["mean", "std"]})
df_noise = df_noise.groupby(["n_init", "noise_level"]).agg({"best": ["mean", "std"]})
print("GP with noise")
display(df_noise.unstack().style.format("{:.2f}").background_gradient(cmap='viridis'))
print("GP without noise")
display(df_no_noise.unstack().style.format("{:.2f}").background_gradient(cmap='viridis'))

GP with noise

GP without noise